### PR TITLE
Wizard For Fixing .xproj Artifacts Output File Path

### PR DESCRIPTION
**Pull request by RehanSaeed**
See https://github.com/ligershark/side-waffle/issues/326

Appveyor is complaining because I had to add a dependency on Microsoft.Visual Studio.Shell which it can't find. Any ideas on how I can fix this?

### CODE REVIEW

**Comment by sayedihashimi** [comment]
Thanks I will fix build issue and comment/merge tomorrow.

**Comment by RehanSaeed** [comment]
Sounds great! Thanks, @sayedihashimi.

**Comment by RehanSaeed** [comment]
I'd like to employ this new feature this weekend. Any idea when the NuGet package will get updated?

**Comment by sayedihashimi** [comment]
@RehanSaeed I will release it today. I'll reply here when I do. I'm working through getting the build to run in CI.

**Comment by sayedihashimi** [comment]
@RehanSaeed it's been released as version `TemplateBuilder 1.1.4.7-beta`. It should be available from nuget.org in a few minutes.

**Comment by RehanSaeed** [comment]
Cool, thanks!

**Comment by sayedihashimi** [comment]
@RehanSaeed I think I will rev the assembly version and nuget version independently. If they are always matched then everytime we update the pkg we will need to update .vstemplate files.
I'm going to merge your other PR and then update version number to 1.2.0.0 and then only rev that whenever we need to update the number. Let me know if you disagree.

**Comment by RehanSaeed** [comment]
Sounds good to me. I'll give it a try as soon as I get some time.

**Comment by RehanSaeed** [comment]
Works fine. I've released a new version of Boilerplate including this change. Will report back if I get people reporting issues.

**Pull request merged**
